version: '3.8'

services:
  strapi:
    image: strapi/strapi
    container_name: strapi_mysql
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_NAME: ${DATABASE_NAME:-strapidb}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapidb_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-P@ssw0rd}
      DATABASE_SSL: ${DATABASE_SSL:-false}
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
